/* LogicomySql: */

CREATE TABLE USUARIO (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    foto_perfil VARCHAR(500),
    nome VARCHAR(75),
    email VARCHAR(75),
    senha VARCHAR(30)
);

CREATE TABLE ESTABELECIMENTO (
    FK_selo_id_PK INTEGER,
    foto_banner VARCHAR(500),
    latitude VARCHAR(30),
    longitude VARCHAR(30),
    FK_tipo_estabelecimento_id_PK INTEGER,
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(75)
);

CREATE TABLE AVALIACAO (
    dt_avaliacao DATE,
    nota FLOAT,
    FK_ESTABELECIMENTO_id INTEGER,
    FK_USUARIO_id INTEGER
);

CREATE TABLE COMENTARIOS (
    descricao VARCHAR(300),
    dt_comentario DATE,
    FK_ESTABELECIMENTO_id INTEGER,
    FK_USUARIO_id INTEGER
);

CREATE TABLE selo (
    id INTEGER NOT NULL PRIMARY KEY,
    descricao_selo VARCHAR(30)
);

CREATE TABLE tipo_estabelecimento (
    id INTEGER NOT NULL PRIMARY KEY,
    descricao_tipo VARCHAR(30)
);
 
ALTER TABLE ESTABELECIMENTO ADD CONSTRAINT FK_ESTABELECIMENTO_2
    FOREIGN KEY (FK_selo_id_PK)
    REFERENCES selo (id)
    ON DELETE NO ACTION;
 
ALTER TABLE ESTABELECIMENTO ADD CONSTRAINT FK_ESTABELECIMENTO_3
    FOREIGN KEY (FK_tipo_estabelecimento_id_PK)
    REFERENCES tipo_estabelecimento (id)
    ON DELETE NO ACTION;
 
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_1
    FOREIGN KEY (FK_ESTABELECIMENTO_id)
    REFERENCES ESTABELECIMENTO (id)
    ON DELETE CASCADE;
 
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_2
    FOREIGN KEY (FK_USUARIO_id)
    REFERENCES USUARIO (id)
    ON DELETE CASCADE;
 
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_1
    FOREIGN KEY (FK_ESTABELECIMENTO_id)
    REFERENCES ESTABELECIMENTO (id)
    ON DELETE CASCADE;
 
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_2
    FOREIGN KEY (FK_USUARIO_id)
    REFERENCES USUARIO (id)
    ON DELETE CASCADE;